# Generated by Django 4.1.3 on 2023-05-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prduto',
            new_name='Produto',
        ),
    ]
