# Generated by Django 4.1.3 on 2023-06-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_variacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variavel', 'verbose_name_plural': 'Variações'},
        ),
    ]
